# Generated by Django 5.2.3 on 2025-07-11 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0004_skill_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='created',
        ),
    ]
