# Generated by Django 5.2.4 on 2025-07-11 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0006_skill_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='created',
        ),
    ]
