# Generated by Django 5.2.3 on 2025-07-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skill", "0006_skill_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="skill_image",
            field=models.ImageField(blank=True, null=True, upload_to="skill_images/"),
        ),
    ]
