# Generated by Django 5.2.3 on 2025-07-15 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0001_initial"),
        ("skill", "0007_skill_skill_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="skill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review",
                to="skill.skill",
            ),
        ),
    ]
