# Generated by Django 5.2.4 on 2025-07-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_userdetail_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='skills_needed',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='skills_offered',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='availability',
            field=models.CharField(default='location', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetail',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
